### ISSUE TITLE
数据库迁移报错

### ISSUE THREAD

**Issue by holiyo** [atzcl/z#10]
![image](https://user-images.githubusercontent.com/20294419/71789252-debccf00-3064-11ea-9857-4f4e1c54b753.png)
$ ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:run
Error during migration run:
src/app/foundations/ORM/Model/BuildsQueries.ts:43:30 - error TS7016: Could not find a declaration file for module 'sequelize/lib/transaction'. 'D:/midway/ts-midway/node_modules/sequelize/lib/transaction.js' implicitly has an 'any' type.
  Try `npm install @types/sequelize` if it exists or add a new declaration (.d.ts) file containing `declare module 'sequelize/lib/transaction';`

43 import Transaction = require("sequelize/lib/transaction")

**Comment by atzcl** [comment]
ts-node 升级后导致的问题，已 fix，感谢

**Comment by holiyo** [comment]
yarn run v1.21.1
$ ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:run
Error during migration run:
src/app/foundations/Decorators/Validate.ts:29:41 - error TS2339: Property 'all' does not exist on type 'Request'.

29       await ctx.validate(rules, request.all())

**Comment by holiyo** [comment]
![image](https://user-images.githubusercontent.com/20294419/71872119-6df5df80-3156-11ea-8341-38c05c4a5530.png)

**Comment by atzcl** [comment]
@holiyo 我本地跑了下，没问题嚄，可以尝试下升级依赖？

**Comment by holiyo** [comment]
@atzcl 
升级下依赖确实可以了，但是run dev后又有新的问题
D:\midway\z\node_modules\_ts-node@7.0.1@ts-node\src\index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/app/modules/Captcha/Controllers/Captcha.ts(30,42): error TS2339: Property 'cache' does not exist on type 'Application'.
src/app/modules/Captcha/Controllers/Captcha.ts(41,20): error TS2339: Property 'cache' does not exist on type 'Application'.

**Comment by jsl6** [comment]
yarn typeorm migration:run
yarn run v1.17.3
$ ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:run
Error during migration run:
src/app/extend/helper.ts:38:11 - error TS2339: Property 'jwt' does not exist on type 'Application'.

38       app.jwt,
             ~~~
src/app/extend/helper.ts:40:11 - error TS2339: Property 'cache' does not exist on type 'Application'.

40       app.cache,
             ~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
