### ISSUE TITLE
console cli的model template 里引用'@app/foundations/Bases/Model/BaseModel‘应为/ORM/Model?

### ISSUE THREAD

**Issue by 618457** [atzcl/z#13]
/src/console/commands/templates/model里
import { BaseModel, DefaultColumns } from '@app/foundations/Bases/Model/BaseModel';

是否应为
import { BaseModel, DefaultColumns } from '@app/foundations/ORM/Model/'; ？
？？

**Comment by atzcl** [comment]
close 8d490eb58be9ee05a9182599de97389afb7d958a
