### ISSUE TITLE
migration模板里三个引用无效？

### ISSUE THREAD

**Issue by 618457** [atzcl/z#14]
在模板生成的migration里有三个引用，这三个文件没有找到噢，请问是在哪？

import UuidPrimary from '@/app/foundations/migrations/UuidPrimary';
import Timestamps from '@/app/foundations/migrations/Timestamps';
import SoftDeletes from '@/app/foundations/migrations/SoftDeletes';

**Comment by atzcl** [comment]
close 8d490eb58be9ee05a9182599de97389afb7d958a
