### ISSUE TITLE
是否考虑集成接口文档生成工具

### ISSUE THREAD

**Issue by jimizai** [atzcl/z#19]
比如 egg-swagger

**Comment by atzcl** [comment]
看了一圈 egg/midwayjs 关于 swagger 的集成，感觉都不太理想，都是类似 jsdoc 的方式，没有直接使用元数据来收集的，如果你需要，可以参看这个 issue https://github.com/midwayjs/midway/issues/281  集成是非常简单的，另外我已经在转用 nestjs 了，因为 midwayjs 在工具链生态上，比 nestjs 差太多了，达不到开箱即用的程度
