### ISSUE TITLE
SkipPermissionCheck.add 参数为数组时有bug

### ISSUE THREAD

**Issue by jimizai** [atzcl/z#22]
static add(path: string | string[]) {
   isArr(path) ? path.forEach(this.addRoutePaths) : this.addRoutePaths(path);
}
应该改为

static add(path: string | string[]) {
    isArr(path)
      ? path.forEach((url) => this.addRoutePaths(url))
      : this.addRoutePaths(path);
  }

**Comment by atzcl** [comment]
非常感谢，已经修复了，这是个低级的 this 指向问题  😂
