### ISSUE TITLE
命令行创建模块报错

### ISSUE THREAD

**Issue by z1769057083** [atzcl/z#23]
![1589880533(1)](https://user-images.githubusercontent.com/22109663/82309860-3ea18a00-99f6-11ea-84a3-301275cd03e7.jpg)

npm run z mm -name test

> z@0.0.2 z E:\学习\z                                                            > ts-node -r tsconfig-paths/register ./src/console/index.ts "mm" "test"                                                                                                                                                                            😣 无法识别的选项：test
--

**Comment by atzcl** [comment]
yargs 的问题，使用参数别名即可，`npm run z mm -n test`

**Comment by z1769057083** [comment]
> yargs 的问题，使用参数别名即可，`npm run z mm -n test`


$ npm run z mm -n test                                                                                                                                            > z@0.0.2 z E:\学习\z                                                            > ts-node -r tsconfig-paths/register ./src/console/index.ts "mm" "test"                                                                                                                                                                            😣 无法识别的选项：test
--

这样也不行

**Comment by atzcl** [comment]
@z1769057083 npm 需要在 option 前面加多一个 --
```
npm run z mm -- --name test  or npm run z make:module -- -n test
```

或者直接使用 yarn 会更加方便
