### ISSUE TITLE
问题: redis 创建挂载在app 而不是agent上

### ISSUE THREAD

**Issue by jimizai** [atzcl/z#24]
是否应该将redis 创建为app  addSingleton 而不是挂载在agent上
`
  redis: {
    client: {
      ...redisBaseConfig,
      db: '5',
    },
    agent: true,
  },
`

**Comment by atzcl** [comment]
因为 Agent 在单机上只会创建一次，而 App Worker 不一定（多进程的时候会是多个），另外 App Worker 在异常没有被正常消化的时候，是会崩溃重启的，所以类似 redis、mysql 的创建最好就是放在 Agent 上，这里直接用的是 egg-redis，agent 跟 app 都可以自由切换的
