### ISSUE TITLE
ts error 7053

### ISSUE THREAD

**Issue by taco-wang** [atzcl/z#25]
我就clone 了这个项目 复制了config.default.ts 
yarn Dev
![image](https://user-images.githubusercontent.com/16523103/83473040-3f88f000-a4bb-11ea-9292-f4bf740aa759.png)
src/app/extend/helper.ts(240,11): error TS7053: Element implicitly has an 'any' type because expression of type '"pidField"' can't be used to index type 'unknown'.
  Property 'pidField' does not exist on type 'unknown'.
src/app/extend/helper.ts(245,16): error TS2339: Property 'value' does not exist on type 'V'.
src/app/extend/helper.ts(245,24): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'unknown'.
  No index signature with a parameter of type 'string' was found on type 'unknown'.
src/app/extend/helper.ts(246,16): error TS2339: Property 'label' does not exist on type 'V'.
src/app/extend/helper.ts(246,24): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'unknown'.
  No index signature with a parameter of type 'string' was found on type 'unknown'.
src/app/extend/helper.ts(252,9): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'unknown'.
  No index signature with a parameter of type 'string' was found on type 'unknown'.
src/app/extend/helper.ts(256,32): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'unknown'.
  No index signature with a parameter of type 'string' was found on type 'unknown'.

**Comment by atzcl** [comment]
你的 typescript/ts-node  的版本分别是？

**Comment by taco-wang** [comment]
typescirpt ^3.8.3 
"ts-node": "^8.9.0",

**Comment by atzcl** [comment]
ts 的版本导致的，已经修正，更新下代码试一下~
