### ISSUE TITLE
NaN 不能用全等判断

### ISSUE THREAD

**Issue by super918180** [atzcl/z#27]
![image](https://user-images.githubusercontent.com/20025505/83585847-74f61200-a57d-11ea-8287-54e8d60325c7.png)
![image](https://user-images.githubusercontent.com/20025505/83585879-8ccd9600-a57d-11ea-9388-a912afe4083d.png)

大佬加个微信呗，一起学习
![image](https://user-images.githubusercontent.com/20025505/83585947-bf778e80-a57d-11ea-9dab-cda9e44ade7f.png)

**Comment by atzcl** [comment]
忘记了还有这个坑 😂😂 修正了

**Comment by atzcl** [comment]
好友已加~
