### ISSUE TITLE
一切运行成功无报错，打开404Not Found

### ISSUE THREAD

**Issue by TinChak** [atzcl/z#3]
![image](https://user-images.githubusercontent.com/5918515/41073749-4745e7dc-6a37-11e8-975a-c9aeb76f0fe8.png)
![image](https://user-images.githubusercontent.com/5918515/41073762-5163eaf2-6a37-11e8-819d-f01b9515305b.png)

**Comment by atzcl** [comment]
hi，是因为 `.gitignore` 文件有排除 `.js` 的规则，所以导致路由文件没有上传，现在补全了，请更新试下

**Comment by TinChak** [comment]
可以访问了，谢谢。如果有更完整的项目供学习就好了。

egg-sequelize 不支持多数据源，这个比thinkjs坑。。。
