### ISSUE TITLE
Error when "yarn run"

### ISSUE THREAD

**Issue by SleepDevil** [atzcl/z#30]
![Snipaste_2021-01-31_12-19-03](https://user-images.githubusercontent.com/55879038/106374454-a0582780-63be-11eb-81b9-053fcd9ec237.png)
![Snipaste_2021-01-31_12-19-40](https://user-images.githubusercontent.com/55879038/106374455-a0582780-63be-11eb-9359-82dc3f758b67.png)
运行yarn dev时出现如图所示类型错误。

**Comment by atzcl** [comment]
crypto 的部分 ts 类型变更导致的，已经调整了，更新下代码看看
