### ISSUE TITLE
多模块里面至少一个services怎么样才能挂载Context？

### ISSUE THREAD

**Issue by wscart** [atzcl/z#4]
你好，我看了你写的这个项目挺好，值得我参考学习，但是我这几天遇到了有问题，想请你帮忙看一下怎么解决这个问题，谢谢

问题描述
1、建了app/modules,modules都是mvc模式的，modeules里面有对应业务逻辑的文件，比如登录，用户管理，权限管理，角色管理。。。等，每个文件都有对应的路由配置，基于egg-router-plus的实现方法。

2、举例在app/modules/users，users里面分别有controllers文件夹，services文件夹，router配置文件。在controllers上请求访问到ctx.modules.users.services.index(),但是访问这个ctx.modules结果是undefined。

操作问题：
eggjs如何将这个定义模块挂载在context上，让任何一个模块里的controllers上请求访问services，services即是ctx.modules.users.services。

**Comment by atzcl** [comment]
@wscart 当前多模块是基于 egg 的 loader 来实现自定义加载的，所以你看下 `app/lib/loader.ts` 的 `loadModules `  方法就明白了

**Comment by atzcl** [comment]
后面应该考虑下使用 IoC/DI 来实现，具体参考：[midway](https://github.com/midwayjs/midway/)、[nestjs](https://github.com/nestjs/nest)

**Comment by wscart** [comment]
嗯，我好好研究，谢谢你 @atzcl

**Comment by atzcl** [comment]
@wscart 我最近在选择用 `midway` or `nestjs` 重构，到时候会更新上来的，到时候你也可以参考下
