### ISSUE TITLE
报错  TSError: [egg-core] load file: src\config\config.default.ts, error: ⨯ Unable to compile TypeScript:

### ISSUE THREAD

**Issue by yay2008** [atzcl/z#6]
之前的版本没问题 更新到最新版后就报这个错

TSError: [egg-core] load file: src\config\config.default.ts, error: ⨯ Unable to compile TypeScript:
src/config/config.default.ts(79,9): error TS7018: Object literal's property 'connectionMiddleware' implicitly has an 'any[]' type.
src/config/config.default.ts(80,9): error TS7018: Object literal's property 'packetMiddleware' implicitly has an 'any[]' type.
src/config/config.default.ts(83,9): error TS7018: Object literal's property 'connectionMiddleware' implicitly has an 'any[]' type.
src/config/config.default.ts(84,9): error TS7018: Object literal's property 'packetMiddleware' implicitly has an 'any[]' type.

**Comment by atzcl** [comment]
@yay2008 已修复，这是缺少了类型定义导致的

另外项目代码调整，建议重新拉取
