### ISSUE TITLE
src/app/foundation/Bases/BaseControllers.ts中config.default的修改

### ISSUE THREAD

**Issue by 618457** [atzcl/z#8]
src/app/foundation/Bases/BaseControllers.ts中

import { adminPrefix } from '@my_config/config.default';
应为
import { adminPrefix } from '@/config/config.default';

**Comment by atzcl** [comment]
@618457 这是忘了在 tsconfig.json paths 里面添加对应的路径别名定义，另外，现在对项目进行了很多的调整，可以 pull 一下，然后重新安装依赖看看

**Comment by 618457** [comment]
主要是我看在别的地方config没用别名，想着两个不同的路径可能会统一用其中一种。看见更新喜出望外，已pull，哈哈。
